### ISSUE TITLE
Last tag is nearly one year old

### ISSUE THREAD

**Issue by choeffer** [dtjohnson/aws-azure-login#237]
I think we need to create a new tag to publish all the updates from main. If using npm install, I still get the old dependencies, and not the updated once which have been merged a few weeks ago.

**Comment by choeffer** [comment]
I currently have the problem that the "latest" one (3.4.0) installed with `npm install aws-azure-login` throughs an error

```
[choeffer@localhost ]$ npm install aws-azure-login
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest

added 179 packages, and audited 180 packages in 24s

29 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
[choeffer@localhost ]$ aws-azure-login --mode cli --profile systems-dev
Logging in with profile 'systems-dev'...
Using AWS SAML endpoint https://signin.aws.amazon.com/saml
Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.
    at CDPSession.send (/home/choeffer/Dokumente/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:35)
    at Page._screenshotTask (/home/choeffer/Dokumente/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1927:28)
    at /home/choeffer/Dokumente/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1924:62
```

and the latest one installed via git is not working at all

```
[choeffer@localhost ]$ npm install git+ssh://git@github.com/DTN-Public/aws-azure-login
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 183 packages, and audited 184 packages in 1m

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[choeffer@localhost ]$ aws-azure-login --mode cli --profile systems-dev
bash: /home/choeffer/Dokumente/node_modules/.bin/aws-azure-login: Datei oder Verzeichnis nicht gefunden
```

**Comment by Benedikt0x4C** [comment]
I've been able to get it to work. It's hacky, but better than no working version at all. I've been getting the same error `Error: Protocol error (Target.activateTarget)`. This is due to an issue in older `puppeteer` versions: https://github.com/puppeteer/puppeteer/issues/7455.

To get a working version again, I modified the `package.json`:
1. Delete your current `aws-azure-login`, e.g. `sudo npm uninstall -g aws-azure-login`
2. Download the latest release version: https://github.com/DTN-Public/aws-azure-login/releases/tag/v1.13.0
3. Unpack and modify `package.json` changing the line with the `puppeteer` dependency to:
```
"puppeteer": "^13.6.0"
```
4. Compress the modified version as a .tgz archive again
5. Install the modified version, e.g. `sudo npm install -g ./aws-azure-login-1.13.0-patched.tgz`

Tested and working with latest NPM v8.11.

I also quickly tested simply updating all dependencies using the latest versions as specified in: https://github.com/DTN-Public/aws-azure-login/blob/main/package.json but that causes problems too. So, updating the `puppeteer` dependency only seems to be a viable workaround right now.
